/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fileTransfer_FileTransfer */

#ifndef _Included_fileTransfer_FileTransfer
#define _Included_fileTransfer_FileTransfer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fileTransfer_FileTransfer
 * Method:    fileTransfer
 * Signature: (II[I)I
 */
JNIEXPORT jbyteArray JNICALL Java_fileTransfer_FileTransfer_fileTransfer (JNIEnv *, jobject, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
